name: artifcats-workflow
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm install
              working-directory: ./Practice Project
            - name: npm lint
              run: npm run lint
              working-directory: ./Practice Project
            - name: Test code
              run: npm test
              working-directory: ./Practice Project
    build:
        runs-on: ubuntu-latest
        needs: test
        outputs:
            script-file: ${{steps.publish.outputs.script-file}}
        steps:
          - name: Get code
            uses: actions/checkout@v4
          - name: Install dependencies
            run: npm install
            working-directory: ./Practice Project
          - name: Build code
            run: npm run build
            working-directory: ./Practice Project
          - name: generate outputs
            id: publish
            working-directory: ./Practice Project
            run: find dist/assets/*.js -type f -execdir echo 'script-file={}'>> GITHUB_OUTPUT ';'
          - name: upload artifacts
            uses: actions/upload-artifact@v4
            with:
                name: dist-files
                path: ./Practice Project/dist
    Deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Get Build artifacts
            uses: actions/download-artifact@v4
            with:
               name: dist-files
               path: ./Practice Project/dist
          - name: output contents
            run: ls
            working-directory: ./Practice Project/dist
          - name: display filename
            run: ${{needs.build.outputs.script-file}}
          - name: Deploy
            run: echo "Deploying...."
    